alias prompt-pick='$DOLET_JS_DIR/promptPick.js'
alias aef='nano $DOLET_FUNCTION_FILE'
alias ae="nano $DOLET_ALIAS_FILE"
alias af='alias | grep'
alias bz="cd ~/pg/biz_modern_pages"
alias clean='rm **/._*'
alias contributors='git shortlog -sne'
alias dedupe='awk '\''!x[$0]++'\'''
alias fdm='fd master HEAD'
alias ga="git add -p"
alias gam="git commit --amend --no-edit"
alias gfl='git log --all --full-history --'
alias got='git'
alias gp="git push origin HEAD --force"
alias gpo="git push origin HEAD"
alias uniqHistory="HISTTIMEFORMAT='' HISTCONTROL=ignoredups history | cut -c 8- | grep -v 'grep\|hf\|uniqHistory' | tac | dedupe"
alias hf="uniqHistory | grep"
alias he='prompt-pick ask "Pick a command" "$(uniqHistory)" && $(cat $DOLET_ANSWER_FILE)'
alias ipy="ipython -i tools/interactive.py"
alias jj="cd ~/pg/yelp-main"
alias last-visited-branch='visited-branch | dedupe'
alias load="sort $DOLET_ALIAS_FILE -o $DOLET_ALIAS_FILE && source $BASH_PROFILE_FILE"
alias mr='mm && pgctl restart'
alias ms="sandbox --minimal"
alias pf='cat package.json | grep '
alias pgd="pgctl debug uwsgi"
alias pgr="pgctl restart"
alias pgs="pgctl status"
alias re="gp && review-branch"
alias release='pkg-release --no-merge -v'
alias root='cd ~'
alias rt='make && pgctl restart'
alias sa='cat $DOLET_ALIAS_FILE'
alias ss='git push origin HEAD --force && seagull-run'
alias tfd="fd HEAD^1 HEAD | grep test"
alias visited-branch="git reflog | grep -o 'checkout: moving from .* to ' | sed -e 's/checkout: moving from //' -e 's/ to $//' | head -20"
alias yc='rm -rf yarn.lock node_modules/'
alias yk='yelp/testing/tools/karma.py'
alias yr='yc && yarn && yarn-tools fix-duplicates yarn.lock && make'
alias gitnav='prompt-pick ask "Pick directory" "$(findGit ~)" && cd "$(cat $DOLET_ANSWER_FILE)"'
alias gc='prompt-pick ask "Pick branch" "$(git branch | grep -v '\''*'\'')" && git checkout "$(cat $DOLET_ANSWER_FILE)"'
alias devbox='ssh -A $dev11'
alias sync-devbox='sshfs -o IdentityFile=~/.ssh/id_rsa $dev11:/nail/home/nghia/pg ~/pg  -oauto_cache,reconnect'
alias agentup='ssh-add ~/.ssh/id_rsa'
alias init='agentup && sync-devbox && devbox'
